# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-20.04

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Use Python 3.8'

- script: |
    npm install
    npm run build
  displayName: 'Install npm dependencies and build frontend'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt --no-cache-dir
    python webapp.py collectstatic --noinput
  displayName: 'python install'

- task: CopyFiles@1
  inputs:
    SourceFolder: './'
    Contents: |
     **
     !node_modules/**
     !static/**
     !src/**
     !__pycache__/**
     !README.md
     !.gitignore
     !package*.json
     !pipeline-*.yml
     !public/index.html
     !build/index.html
    TargetFolder: '$(build.artifactstagingdirectory)'
    CleanTargetFolder: true
    OverWrite: true
    flattenFolders: false
    
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(build.artifactstagingdirectory) # dist or build files
    ArtifactName: 'package'
    publishLocation: 'Container'